### PR TITLE
CLO base

### PR DESCRIPTION
**Pull request by matentzn**
This pull request contains the functionality to generate CLO base, and some additional stuff that you can (but dont have to) use for quality control, like reports of missing labels etc. 

In your clo.owl, I can see the following 2 imports:
<owl:imports rdf:resource="http://purl.obolibrary.org/CLO-NICR.owl"/>
<owl:imports rdf:resource="http://purl.obolibrary.org/obo/clo/cellline_import.owl"/>

I assume now that they do NOT belong to CLO, and should be considered as external. So the base file, which should contain only base axioms, currently only contains axioms from clo.owl. Let me know if they do contain native CLO axioms you consider base axioms!

What I have not yet done is getting rid of external axioms. I am out of time now, but perhaps Edison could give this a shot? Manually I think is safer than using tools. That way you can double check that the information is really not needed.

### CODE REVIEW

**Comment by matentzn** [comment]
The instruction on how to create the base release are in src/ontology/README.md!

**Comment by matentzn** [comment]
(This pull request does NOT change any axioms in PR at the moment at all)

Please let me know about the imports and if you need further help!

**Comment by yongqunh** [comment]
The 2 imports are indeed part of CLO:
<owl:imports rdf:resource="http://purl.obolibrary.org/CLO-NICR.owl"/>
<owl:imports rdf:resource="http://purl.obolibrary.org/obo/clo/cellline_import.owl"/>
We probably need to merge them to CLO.

**Comment by yongqunh** [comment]
Probably we need to merge these two import cell line ontology files to CLO, and then do all the base generation process again.
What do you think?

**Comment by matentzn** [comment]
OK, so what I did now is this:
clo.owl + CLO-NCIR + cellline_import now together make up clo-base.owl

I also removed a lot of foreign axioms from all three ontologies above. To not cause problems, instead of deleting them, I added them as separate ontologies (clo-foreign, CLO-NCIR-foreign, cellline_import-foreign), they are now being imported by clo.owl. You should devote some time probably to review those and delete them if it is safe to do so. 

If you click [here](https://github.com/CLO-ontology/CLO/pull/46/files), you can see that see that the axioms from the ontologies above to the -foreign counterparts. Do you think that is okay?

**Comment by matentzn** [comment]
@yongqunh Was there anything I can help with here? Do you need more information/assistance?

**Comment by yongqunh** [comment]
There are some decisions to make. For example,  CLO-NCIR is generated by another group. I will probably need to contact them to make sure that they agree and any changes they will make follow some rules.

**Comment by matentzn** [comment]
Ok thanks! :) Would you be happy in the meantime to host the `clo-base.owl` only (which contains the proposed changes)? We won't commit any changes to other files until you have talked to your collaborators and the changes have been vetted in detail. What do you think?

**Comment by matentzn** [comment]
Hey @yongqunh 
Do you want to sit together and finish the PR, or do you think it just wont happen? I will realise then what I need (clo-base) in some different way :) Thanks!

**Comment by e4ong1031** [comment]
Hi @matentzn 

I have discussed with Oliver. Instead of importing (clo-foreign, CLO-NCIR-foreign, cellline_import-foreign) back to clo.owl, could you simply make another folder under CLO, like CLO/CLO-base? In that case, you can generate and keep the clo-base.owl and all other relevant files in this folder without touching the original CLO files.

As Oliver said in previous comments, there are a lot of dependencies/agreements for the clo.owl, and we would like to keep it as-is.

**Comment by matentzn** [comment]
Hm, this is not really possible unfortunately.. We cant have a base with foreign axioms, and this pull request was an attempt to get rid of those! I can't just create a base file elsewhere; it will soon be out of date with the normal CLO.. This pull request would have not really changed anything for you (other than moving non-CLO axioms out of CLO), but I can see that resources are limited, and you would prefer to wait until you can properly review the consequences of this. Please contact me again if you have time to go over this together once more :) This is really about making it possible to use CLO downstream in our other ontologies, which I am sure you would also like. Lets revisit this again when the pressure from grants and interoperability requirements rises again! :)

**Pull request closed without merging**
